//! Qwen Image generation/editing and LTX video in Rust on Candle tensor primitives.
//! No Python process, C++ diffusion runtime, or model-format conversion.
#![forbid(unsafe_code)]

pub mod math;
pub mod pipeline;
pub mod reference;
pub mod residency;
pub mod schedule;
pub mod text;
pub mod transformer;
#[cfg(feature = "webgpu")]
pub mod wgpu_weights;
#[cfg(feature = "webgpu")]
pub mod qwen_wgpu;
#[cfg(feature = "webgpu")]
pub mod vae_wgpu;
#[cfg(feature = "webgpu")]
pub mod text_wgpu;
#[cfg(feature = "webgpu")]
pub mod vision_wgpu;
#[cfg(feature = "webgpu")]
pub mod ltx_wgpu;
#[cfg(feature = "webgpu")]
pub mod ltx_vae_wgpu;
#[cfg(feature = "webgpu")]
pub mod ltx_text_wgpu;
pub mod vae;
pub mod vision;
pub mod weights;
pub mod lora;
mod comfy_quant;
pub mod ltx;
pub mod sdxl;
pub mod music;
pub mod tts;
pub mod sound;
#[cfg(feature = "webgpu")]
pub mod sound_wgpu;
#[cfg(feature = "webgpu")]
pub mod tts_wgpu;
#[cfg(feature = "webgpu")]
pub mod qwen3_wgpu;
#[cfg(feature = "webgpu")]
pub mod codec_wgpu;
#[cfg(feature = "webgpu")]
pub mod music_wgpu;
#[cfg(feature = "webgpu")]
pub mod music_lm_wgpu;
#[cfg(feature = "webgpu")]
pub mod model3d_wgpu;
pub mod model3d;
pub mod birefnet;
#[cfg(feature = "webgpu")]
pub mod birefnet_wgpu;
pub mod esrgan;
#[cfg(feature = "webgpu")]
pub mod esrgan_wgpu;
pub mod picture;
pub mod klein;
