/**
 * Build the headless CLI into a single Node ESM bundle (dist/oaiy.mjs).
 *
 * Two jobs:
 *  1. Codegen `src/generated/bundled-modules.ts` — the Node equivalent of the
 *     web build's `import.meta.glob` module discovery (esbuild has no glob), but
 *     WITHOUT each module's React `ui/index.ts`, since headless never renders.
 *  2. Bundle with an alias plugin mirroring ui/vite.config.ts: the same
 *     `oaiy-core` / `oaiy-core/modules/*` source resolution, with `@tauri-apps/*`
 *     pointed at the Node host (src/node-host/*) instead of the browser shim.
 *  3. Ship the ZIPP engine: verify the installed release (the same check ui's
 *     tests run), bake its identity into every bundle as `define`s, stage the
 *     .wasm and notices to dist/zipp/, and build the worker shell that runs
 *     flows on it (dist/oaiy-zipp-worker.mjs). Nothing here names a release:
 *     the identity is whatever SOURCE.json the installer wrote.
 */
import esbuild from 'esbuild';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { checkInstall, VARIANTS } from '../scripts/fetch-zipp-release.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(__dirname, '..'); // oaiy-web/
const uiSrc = path.join(repo, 'ui', 'src');
const uiVendorCore = path.join(repo, 'ui', 'vendor', 'oaiy-core');
const bundledModules = path.join(uiSrc, 'bundled-modules');
const nodeHost = path.join(__dirname, 'src', 'node-host');

const fwd = (p) => p.replace(/\\/g, '/');

// --- 1. Codegen: static bundled-module registration ----------------------
export function genBundledModules() {
  const ids = fs
    .readdirSync(bundledModules, { withFileTypes: true })
    .filter((d) => d.isDirectory() && fs.existsSync(path.join(bundledModules, d.name, 'module.json')))
    .map((d) => d.name)
    .sort();

  const L = ['// AUTO-GENERATED by cli/esbuild.mjs — do not edit.'];
  L.push("import { registerBundledModules, getModuleLoader, loadBundledModules } from 'oaiy-core';");
  L.push("import type { BundledModule, ModuleLoader, ModuleManifest, NodeDefinition } from 'oaiy-core';");
  const entries = [];

  for (const id of ids) {
    const safe = id.replace(/[^a-zA-Z0-9_]/g, '_');
    const dir = path.join(bundledModules, id);
    const imp = (v, file) => L.push(`import ${v} from ${JSON.stringify(fwd(path.join(dir, file)))};`);

    imp(`manifest_${safe}`, 'module.json');

    const nodesDir = path.join(dir, 'nodes');
    const nodeVars = [];
    if (fs.existsSync(nodesDir)) {
      for (const [i, nf] of fs
        .readdirSync(nodesDir)
        .filter((f) => f.endsWith('.json'))
        .sort()
        .entries()) {
        const v = `node_${safe}_${i}`;
        nodeVars.push(v);
        L.push(`import ${v} from ${JSON.stringify(fwd(path.join(nodesDir, nf)))};`);
      }
    }

    let runtimeVar = 'undefined';
    let compilerVar = 'undefined';
    if (fs.existsSync(path.join(dir, 'runtime.ts'))) {
      runtimeVar = `runtime_${safe}`;
      imp(runtimeVar, 'runtime.ts');
    }
    if (fs.existsSync(path.join(dir, 'compiler.ts'))) {
      compilerVar = `compiler_${safe}`;
      imp(compilerVar, 'compiler.ts');
    }

    entries.push(
      `  { manifest: manifest_${safe} as unknown as ModuleManifest, nodes: [${nodeVars.join(', ')}] as unknown as NodeDefinition[], runtime: ${runtimeVar}, compiler: ${compilerVar} }`,
    );
  }

  L.push('');
  L.push('let loaded: ModuleLoader | null = null;');
  L.push('export async function loadNodeBundledModules(): Promise<ModuleLoader> {');
  L.push('  if (loaded) return loaded;');
  L.push('  const modules: BundledModule[] = [');
  L.push(entries.join(',\n'));
  L.push('  ];');
  L.push('  registerBundledModules(modules);');
  L.push('  const loader = getModuleLoader();');
  L.push('  await loadBundledModules(loader, modules);');
  L.push('  loaded = loader;');
  L.push('  return loader;');
  L.push('}');

  const genDir = path.join(__dirname, 'src', 'generated');
  fs.mkdirSync(genDir, { recursive: true });
  fs.writeFileSync(path.join(genDir, 'bundled-modules.ts'), L.join('\n') + '\n');
  return ids.length;
}

// --- 2. Alias plugin (mirrors ui/vite.config.ts resolve.alias) -----------
function resolveWithExt(base) {
  const cands = [
    base,
    base + '.ts',
    base + '.tsx',
    base + '.js',
    base + '.json',
    path.join(base, 'index.ts'),
    path.join(base, 'index.tsx'),
  ];
  for (const c of cands) {
    try {
      if (fs.statSync(c).isFile()) return c;
    } catch {
      /* keep trying */
    }
  }
  return null;
}

export const aliasPlugin = {
  name: 'oaiy-aliases',
  setup(build) {
    // @tauri-apps/* → Node host (the only two the engine graph imports).
    build.onResolve({ filter: /^@tauri-apps\/api\/core$/ }, () => ({
      path: path.join(nodeHost, 'core.ts'),
    }));
    build.onResolve({ filter: /^@tauri-apps\/plugin-sql$/ }, () => ({
      path: path.join(nodeHost, 'sql.ts'),
    }));

    // oaiy-core/modules/* → web bundled-module sources (first match wins).
    build.onResolve({ filter: /^oaiy-core\/modules\// }, (a) => {
      const sub = a.path.replace(/^oaiy-core\/modules\//, '');
      const r = resolveWithExt(path.join(bundledModules, sub));
      return r ? { path: r } : undefined;
    });
    // bare oaiy-core → vendored source index.
    build.onResolve({ filter: /^oaiy-core$/ }, () => ({
      path: path.join(uiVendorCore, 'src', 'index.ts'),
    }));
    // every other oaiy-core/* subpath → vendored source tree.
    build.onResolve({ filter: /^oaiy-core\// }, (a) => {
      const sub = a.path.replace(/^oaiy-core\//, '');
      const r = resolveWithExt(path.join(uiVendorCore, sub));
      return r ? { path: r } : undefined;
    });
  },
};

// --- 3. The ZIPP engine the CLI ships -------------------------------------
// The web-python bundle of the installed release (ui/vendor/zipp-wasm-python,
// gitignored; `npm run build` and `npm test` run `--ensure` first). The
// install is checked the way ui's tests check it, and its SOURCE.json is the
// only source of the engine's identity — no sha, revision or tag is written
// here, so a new release needs no edit.
const ZIPP_VARIANT = VARIANTS.find((v) => v.suffix === 'web-python');
if (!ZIPP_VARIANT) throw new Error('fetch-zipp-release.mjs no longer describes the web-python bundle');
const zippVendor = path.join(repo, 'ui', 'vendor', ZIPP_VARIANT.folder);
// Staged beside the CLI: the engine, its profile, the installer's record, and
// the notices any redistribution of this bundle must carry.
const ZIPP_STAGED = ['zipp_wasm_bg.wasm', 'PROFILE.json', 'SOURCE.json', 'LICENSE-APACHE', 'THIRD_PARTY_LICENSES.txt'];
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');

let zippIdentityCache = null;
/** Verify the install (throws when it does not check) and read its identity. */
export function zippIdentity() {
  if (zippIdentityCache) return zippIdentityCache;
  const source = checkInstall(zippVendor, ZIPP_VARIANT);
  zippIdentityCache = {
    name: 'zipp',
    release: source.release,
    version: source.version,
    revision: source.revision,
    variant: source.variant,
    bundle: source.bundle,
    wasmSha256: source.sha256,
    glueSha256: source.glueSha256,
    languages: source.languages,
  };
  return zippIdentityCache;
}

/** The identity as esbuild `define`s (src/types/shared-source-globals.d.ts declares them). */
export function zippDefines() {
  const identity = zippIdentity();
  return {
    __ZIPP_WASM_SHA256__: JSON.stringify(identity.wasmSha256),
    __ZIPP_ENGINE__: JSON.stringify(JSON.stringify(identity)),
  };
}

/**
 * Stage dist/zipp/ and build dist/oaiy-zipp-worker.mjs. The staged .wasm is
 * hashed AFTER the copy — those bytes are what the CLI checks at run time
 * against the define, so they are checked here against the same digest.
 */
export async function buildZippAssets({ dist = path.join(__dirname, 'dist'), logLevel = 'info' } = {}) {
  const identity = zippIdentity();
  const outDir = path.join(dist, 'zipp');
  fs.mkdirSync(outDir, { recursive: true });
  for (const name of ZIPP_STAGED) {
    fs.copyFileSync(path.join(zippVendor, name), path.join(outDir, name));
  }
  const staged = sha256(fs.readFileSync(path.join(outDir, 'zipp_wasm_bg.wasm')));
  if (staged !== identity.wasmSha256) {
    throw new Error(`dist/zipp/zipp_wasm_bg.wasm has sha256 ${staged} after the copy, not ${identity.wasmSha256}`);
  }
  await esbuild.build({
    entryPoints: [path.join(__dirname, 'src', 'zipp', 'workflow-worker.ts')],
    outfile: path.join(dist, 'oaiy-zipp-worker.mjs'),
    logLevel,
    ...commonBuildOptions,
  });
  return identity;
}

// Build options shared by the CLI bundle and the engine-level tests (test/*.ts that
// import the real createEngine + node-host), so the tests resolve the exact same
// @tauri-apps→node-host + oaiy-core aliases the CLI does.
export const commonBuildOptions = {
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: true,
  plugins: [aliasPlugin],
  // Vite-isms that appear in shared code but mean nothing in Node.
  define: {
    'import.meta.env': '{}',
    'import.meta.vitest': 'undefined',
    // The engine identity, in every bundle that can reach src/zipp/artifact.ts
    // (the CLI, the worker shell, the engine-level tests). Computed when this
    // module loads, so a build without a verified ZIPP install fails here.
    ...zippDefines(),
  },
  // Keep node:sqlite (experimental builtin), Playwright (heavy, ships its own
  // browsers), sharp (optional native image lib) and undici (the SSRF guard's
  // pinned-connection HTTP client) as runtime imports rather than bundling them.
  external: ['node:sqlite', 'playwright', 'sharp', 'undici'],
  // The engine sources live under ../ui, so esbuild's normal walk-up from the
  // importing file lands in ui/node_modules — which only exists when the web
  // app happens to be installed alongside. In CI, and on any machine that
  // installs the CLI alone, that directory is absent and oaiy-core's own
  // third-party imports (acorn, uuid) fail to resolve. Fall back to the CLI's
  // node_modules, where package.json declares them.
  nodePaths: [path.join(__dirname, 'node_modules')],
  banner: {
    js: "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);",
  },
};

// --- run (only when invoked directly, e.g. `node esbuild.mjs`) ------------
const isMain = import.meta.url === pathToFileURL(process.argv[1] ?? '').href;
if (isMain) {
  const count = genBundledModules();
  process.stderr.write(`esbuild: generated registration for ${count} bundled modules\n`);
  const engine = await buildZippAssets();
  process.stderr.write(`esbuild: staged ZIPP ${engine.release} (${engine.revision.slice(0, 8)}) to dist/zipp and built dist/oaiy-zipp-worker.mjs\n`);
  await esbuild.build({
    entryPoints: [path.join(__dirname, 'src', 'cli.ts')],
    outfile: path.join(__dirname, 'dist', 'oaiy.mjs'),
    logLevel: 'info',
    ...commonBuildOptions,
  });
  process.stderr.write('esbuild: built dist/oaiy.mjs\n');
}
