//! Build-time CUDA kernel compilation for the engines (ggml-rs-cuda, dsv41-cuda).
//!
//! The engines compiled their kernels with NVRTC at every start, which made them ship
//! NVRTC (89 MB of DLLs) and spend seconds before the first model loaded. Here a build
//! script compiles the same source with the same options, through the same NVRTC, into a
//! cubin (machine code) for each GPU architecture the engine targets, plus PTX for any
//! other GPU, and writes them to `OUT_DIR` beside a Rust table, `<name>_images.rs`, whose
//! `kernel_image` picks one for a device. The engine loads it with the driver alone.

use std::ffi::{c_char, CString};
use std::path::PathBuf;

use cudarc::nvrtc::{result, sys};

/// Compile `src` (`name` in NVRTC's messages) with `options` (as the engine passed them,
/// before the architecture) into a cubin for each compute capability in `cubins`, PTX for
/// the newest one's virtual architecture (for a GPU newer than every cubin) and PTX with
/// NVRTC's default architecture (for one older), in parallel. Panics with NVRTC's log if
/// one does not compile: a build without its kernels is no build.
pub fn build(name: &str, src: &str, options: &[&str], cubins: &[(u32, u32)]) {
    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    let newest = *cubins.iter().max().expect("at least one architecture");
    let mut jobs: Vec<(String, Option<String>, bool)> =
        cubins.iter().map(|&(a, b)| (format!("sm_{a}{b}"), Some(format!("sm_{a}{b}")), true)).collect();
    jobs.push((format!("compute_{}{}", newest.0, newest.1), Some(format!("compute_{}{}", newest.0, newest.1)), false));
    jobs.push(("base".into(), None, false));
    let images: Vec<(String, Vec<u8>)> = std::thread::scope(|s| {
        let handles: Vec<_> = jobs
            .iter()
            .map(|(tag, arch, cubin)| {
                s.spawn(move || {
                    let mut opts: Vec<String> = options.iter().map(|o| o.to_string()).collect();
                    if let Some(a) = arch {
                        opts.push(format!("--gpu-architecture={a}"));
                    }
                    let bytes = compile(name, src, &opts, *cubin).unwrap_or_else(|e| panic!("{name} for {tag}: {e}"));
                    (tag.clone(), bytes)
                })
            })
            .collect();
        handles.into_iter().map(|h| h.join().expect("a kernel compile panicked")).collect()
    });
    let path = |tag: &str| out.join(format!("{name}_{tag}.bin"));
    for (tag, bytes) in &images {
        std::fs::write(path(tag), bytes).expect("write a kernel image");
    }
    let mut table = String::new();
    table.push_str("// Generated by oaiy-cuda-build: the kernels compiled at build time.\n");
    table.push_str("/// A cubin for each compute capability, oldest first.\n");
    table.push_str("const CUBINS: &[((i32, i32), &[u8])] = &[\n");
    let mut sorted = cubins.to_vec();
    sorted.sort_unstable();
    for (a, b) in sorted {
        table.push_str(&format!("    (({a}, {b}), include_bytes!({:?})),\n", path(&format!("sm_{a}{b}"))));
    }
    table.push_str("];\n");
    table.push_str(&format!(
        "/// PTX for compute_{}{}, ending in a NUL: for a GPU newer than every cubin (the driver compiles it).\n",
        newest.0, newest.1
    ));
    table.push_str(&format!("const PTX_NEWEST: &[u8] = include_bytes!({:?});\n", path(&format!("compute_{}{}", newest.0, newest.1))));
    table.push_str("/// PTX for NVRTC's default architecture, ending in a NUL: for a GPU older than every cubin.\n");
    table.push_str(&format!("const PTX_BASE: &[u8] = include_bytes!({:?});\n", path("base")));
    table.push_str(PICK);
    std::fs::write(out.join(format!("{name}_images.rs")), table).expect("write the kernel table");
}

/// The selection, the same in every engine.
const PICK: &str = r#"
/// The kernels for a GPU of compute capability `cc`: its own cubin; else the newest cubin of
/// its major version no newer than it (a cubin runs on the later minors of its major); else
/// PTX, the newest architecture's for a GPU newer than every cubin and the default's for an
/// older one.
pub(crate) fn kernel_image(cc: (i32, i32)) -> &'static [u8] {
    if let Some((_, image)) = CUBINS.iter().rev().find(|((major, minor), _)| *major == cc.0 && *minor <= cc.1) {
        return image;
    }
    if CUBINS.last().is_some_and(|(newest, _)| cc > *newest) { PTX_NEWEST } else { PTX_BASE }
}
"#;

fn compile(name: &str, src: &str, options: &[String], cubin: bool) -> Result<Vec<u8>, String> {
    let src = CString::new(src).map_err(|_| "the source holds a NUL".to_string())?;
    let label = CString::new(name).map_err(|_| "the name holds a NUL".to_string())?;
    let prog = result::create_program(&src, Some(&label)).map_err(|e| format!("{e:?}"))?;
    let out = (|| unsafe {
        if let Err(e) = result::compile_program(prog, options) {
            let log = result::get_program_log(prog).unwrap_or_default();
            let log: Vec<u8> = log.iter().take_while(|&&c| c != 0).map(|&c| c as u8).collect();
            return Err(format!("{e:?} with {options:?}:\n{}", String::from_utf8_lossy(&log)));
        }
        if cubin {
            let mut size = 0usize;
            sys::nvrtcGetCUBINSize(prog, &mut size).result().map_err(|e| format!("{e:?}"))?;
            let mut bytes = vec![0u8; size];
            sys::nvrtcGetCUBIN(prog, bytes.as_mut_ptr() as *mut c_char).result().map_err(|e| format!("{e:?}"))?;
            Ok(bytes)
        } else {
            // With its NUL, as cuModuleLoadData takes PTX text.
            let ptx = result::get_ptx(prog).map_err(|e| format!("{e:?}"))?;
            Ok(ptx.iter().map(|&c| c as u8).collect())
        }
    })();
    unsafe { result::destroy_program(prog) }.map_err(|e| format!("{e:?}"))?;
    out
}
