/**
 * Build the headless CLI into a single Node ESM bundle (dist/oaiy.mjs).
 *
 * Two jobs:
 *  1. Codegen `src/generated/bundled-modules.ts` — the Node equivalent of the
 *     web build's `import.meta.glob` module discovery (esbuild has no glob), but
 *     WITHOUT each module's React `ui/index.ts`, since headless never renders.
 *  2. Bundle with an alias plugin mirroring ui/vite.config.ts: the same
 *     `oaiy-core` / `oaiy-core/modules/*` source resolution, with `@tauri-apps/*`
 *     pointed at the Node host (src/node-host/*) instead of the browser shim.
 */
import esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(__dirname, '..'); // oaiy-web/
const uiSrc = path.join(repo, 'ui', 'src');
const uiVendorCore = path.join(repo, 'ui', 'vendor', 'oaiy-core');
const bundledModules = path.join(uiSrc, 'bundled-modules');
const nodeHost = path.join(__dirname, 'src', 'node-host');

const fwd = (p) => p.replace(/\\/g, '/');

// --- 1. Codegen: static bundled-module registration ----------------------
export function genBundledModules() {
  const ids = fs
    .readdirSync(bundledModules, { withFileTypes: true })
    .filter((d) => d.isDirectory() && fs.existsSync(path.join(bundledModules, d.name, 'module.json')))
    .map((d) => d.name)
    .sort();

  const L = ['// AUTO-GENERATED by cli/esbuild.mjs — do not edit.'];
  L.push("import { registerBundledModules, getModuleLoader, loadBundledModules } from 'oaiy-core';");
  const entries = [];

  for (const id of ids) {
    const safe = id.replace(/[^a-zA-Z0-9_]/g, '_');
    const dir = path.join(bundledModules, id);
    const imp = (v, file) => L.push(`import ${v} from ${JSON.stringify(fwd(path.join(dir, file)))};`);

    imp(`manifest_${safe}`, 'module.json');

    const nodesDir = path.join(dir, 'nodes');
    const nodeVars = [];
    if (fs.existsSync(nodesDir)) {
      for (const [i, nf] of fs
        .readdirSync(nodesDir)
        .filter((f) => f.endsWith('.json'))
        .sort()
        .entries()) {
        const v = `node_${safe}_${i}`;
        nodeVars.push(v);
        L.push(`import ${v} from ${JSON.stringify(fwd(path.join(nodesDir, nf)))};`);
      }
    }

    let runtimeVar = 'undefined';
    let compilerVar = 'undefined';
    if (fs.existsSync(path.join(dir, 'runtime.ts'))) {
      runtimeVar = `runtime_${safe}`;
      imp(runtimeVar, 'runtime.ts');
    }
    if (fs.existsSync(path.join(dir, 'compiler.ts'))) {
      compilerVar = `compiler_${safe}`;
      imp(compilerVar, 'compiler.ts');
    }

    entries.push(
      `  { manifest: manifest_${safe}, nodes: [${nodeVars.join(', ')}], runtime: ${runtimeVar}, compiler: ${compilerVar} }`,
    );
  }

  L.push('');
  L.push('let loaded = null;');
  L.push('export async function loadNodeBundledModules() {');
  L.push('  if (loaded) return loaded;');
  L.push('  const modules = [');
  L.push(entries.join(',\n'));
  L.push('  ];');
  L.push('  registerBundledModules(modules);');
  L.push('  const loader = getModuleLoader();');
  L.push('  await loadBundledModules(loader, modules);');
  L.push('  loaded = loader;');
  L.push('  return loader;');
  L.push('}');

  const genDir = path.join(__dirname, 'src', 'generated');
  fs.mkdirSync(genDir, { recursive: true });
  fs.writeFileSync(path.join(genDir, 'bundled-modules.ts'), L.join('\n') + '\n');
  return ids.length;
}

// --- 2. Alias plugin (mirrors ui/vite.config.ts resolve.alias) -----------
function resolveWithExt(base) {
  const cands = [
    base,
    base + '.ts',
    base + '.tsx',
    base + '.js',
    base + '.json',
    path.join(base, 'index.ts'),
    path.join(base, 'index.tsx'),
  ];
  for (const c of cands) {
    try {
      if (fs.statSync(c).isFile()) return c;
    } catch {
      /* keep trying */
    }
  }
  return null;
}

export const aliasPlugin = {
  name: 'oaiy-aliases',
  setup(build) {
    // @tauri-apps/* → Node host (the only two the engine graph imports).
    build.onResolve({ filter: /^@tauri-apps\/api\/core$/ }, () => ({
      path: path.join(nodeHost, 'core.ts'),
    }));
    build.onResolve({ filter: /^@tauri-apps\/plugin-sql$/ }, () => ({
      path: path.join(nodeHost, 'sql.ts'),
    }));

    // oaiy-core/modules/* → web bundled-module sources (first match wins).
    build.onResolve({ filter: /^oaiy-core\/modules\// }, (a) => {
      const sub = a.path.replace(/^oaiy-core\/modules\//, '');
      const r = resolveWithExt(path.join(bundledModules, sub));
      return r ? { path: r } : undefined;
    });
    // bare oaiy-core → vendored source index.
    build.onResolve({ filter: /^oaiy-core$/ }, () => ({
      path: path.join(uiVendorCore, 'src', 'index.ts'),
    }));
    // every other oaiy-core/* subpath → vendored source tree.
    build.onResolve({ filter: /^oaiy-core\// }, (a) => {
      const sub = a.path.replace(/^oaiy-core\//, '');
      const r = resolveWithExt(path.join(uiVendorCore, sub));
      return r ? { path: r } : undefined;
    });
  },
};

// Build options shared by the CLI bundle and the engine-level tests (test/*.ts that
// import the real createEngine + node-host), so the tests resolve the exact same
// @tauri-apps→node-host + oaiy-core aliases the CLI does.
export const commonBuildOptions = {
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: true,
  plugins: [aliasPlugin],
  // Vite-isms that appear in shared code but mean nothing in Node.
  define: {
    'import.meta.env': '{}',
    'import.meta.vitest': 'undefined',
  },
  // Keep node:sqlite (experimental builtin), Playwright (heavy, ships its own
  // browsers), sharp (optional native image lib) and undici (the SSRF guard's
  // pinned-connection HTTP client) as runtime imports rather than bundling them.
  external: ['node:sqlite', 'playwright', 'sharp', 'undici'],
  banner: {
    js: "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);",
  },
};

// --- run (only when invoked directly, e.g. `node esbuild.mjs`) ------------
const isMain = import.meta.url === pathToFileURL(process.argv[1] ?? '').href;
if (isMain) {
  const count = genBundledModules();
  process.stderr.write(`esbuild: generated registration for ${count} bundled modules\n`);
  await esbuild.build({
    entryPoints: [path.join(__dirname, 'src', 'cli.ts')],
    outfile: path.join(__dirname, 'dist', 'oaiy.mjs'),
    logLevel: 'info',
    ...commonBuildOptions,
  });
  process.stderr.write('esbuild: built dist/oaiy.mjs\n');
}
