//! CUDA kernel source (`kernels.cu`, with `exl3.cu` and `long_attention.cu`), compiled
//! at build time (`build.rs`, through NVRTC) into a cubin per GPU architecture.
//!
//! All kernels are F32 only and unoptimized — naive correct implementations
//! to validate the backend wiring. Real perf comes from later milestones:
//! a tiled GEMM for `linear`, fused attention, on-device tensors so we
//! don't shuttle every op through host memory.

// `kernel_image(cc)`: the images build.rs compiled, one picked for a device.
include!(concat!(env!("OUT_DIR"), "/ggml_images.rs"));

pub const KERNEL_NAMES: &[&str] = &[
    "lora_down_f32",
    "lora_up_add_f32",
    "rope_axes_f32",
    "exl3_moe_in", "exl3_moe_tile", "exl3_moe_route", "exl3_moe_group", "exl3_moe_route_group",
    "exl3_moe_sum", "exl3_moe_lora", "exl3_moe_mid", "exl3_moe_out",
    "exl3_had", "exl3_had_reduce", "exl3_reconstruct", "exl3_tile_32", "exl3_tile_48", "exl3_tile_56", "exl3_tile_64", "exl3_tile_80", "exl3_tile_96",
    "exl3_gemv_generic", "exl3_gemv_32", "exl3_gemv_48", "exl3_gemv_56", "exl3_gemv_64", "exl3_gemv_80", "exl3_gemv_96",
    "linear_q8_0_f32",
    "linear_q8_0_gemv_coop_f32",
    "linear_iq4_nl_f32",
    "linear_iq4_xs_f32",
    "linear_q2_k_f32",
    "linear_q3_k_f32",
    "linear_q4_0_f32",
    "linear_q4_1_f32",
    "linear_q4_k_f32",
    "linear_q5_k_f32",
    "linear_q5_k_gemv_coop_f32",
    "linear_q5_0_f32",
    "linear_q5_0_gemv_coop_f32",
    "linear_q5_1_f32",
    "linear_q5_1_gemv_coop_f32",
    "linear_q6_k_f32",
    "linear_q6_k_gemv_coop_f32",
    "linear_f32",
    "gemm_f32",
    "linear_f32_gemv_coop",
    "rmsnorm_f32",
    "add_inplace_then_rmsnorm_f32",
    "rmsnorm_no_scale_f32",
    "layer_norm_f32",
    "add_bias_last_f32",
    "softmax_last_f32",
    "silu_f32",
    "silu_mul_f32",
    "sigmoid_f32",
    "mul_sigmoid_inplace_f32",
    "gelu_approx_f32",
    "gelu_approx_mul_f32",
    "silu_mul_split_f32",
    // VENDORED-LOCAL: GLM-5.3-Flash.
    "swiglu_clamped_f32",
    "swiglu_clamped_split_f32",
    // VENDORED-LOCAL: GLM-5.3-Flash.
    "batched_gemv_f32",
    // VENDORED-LOCAL: GLM-5.3-Flash.
    "kda_delta_step_f32",
    "gemv_split_q8_0_f32",
    "gemv_split_f32",
    "gemv_split_reduce_f32",
    "gelu_approx_mul_split_f32",
    "tanh_inplace_f32",
    "gaussian_topk_inplace_f32",
    "altup_predict_f32",
    "altup_correct_f32",
    "add_inplace_f32",
    "mul_inplace_f32",
    "mul_scalar_inplace_f32",
    "mul_inplace_broadcast_last_f32",
    "mul_inplace_broadcast_axis0_f32",
    "add_to_axis0_range_f32",
    "add_to_axis0_range_scaled_f32",
    "slice_axis1_2d_f32",
    "rope_f32",
    "rope_partial_neox_f32",
    "repeat_kv_f32",
    "argmax_last_f32",
    "embed_lookup_f32",
    "bmm_qkt_f32",
    "bmm_av_f32",
    "attention_f32",
    "attention_partition_f32",
    "attention_merge_f32",
    "delta_net_conv1d_decode_f32",
    "delta_net_decode_step_f32",
    "delta_net_conv1d_loop_f32",
    "delta_net_step_loop_f32",
    "delta_net_rows_128_f32",
    "delta_net_norm_128_f32",
    "gather_rows_f32",
    "qsa_pool_f32",
    "qsa_block_scores_f32",
    "qsa_sparse_attention_f32",
    "scatter_add_rows_f32",
    "stream_mean_f32",
    "add_rows_scaled_f32",
    "qsa_select_f32",
    "qsa_sparse_partial_f32",
    "qsa_sparse_combine_f32",
    "hc_norm_f32",
    "unpack_f16_f32",
    "half_gemv_f32",
    "split_cols_f32",
    "ple_gate_f32",
    "ple_conv_f32",
    "hc_apply_norm_f32",
    "hc_down_gates_f32",
    "hc_up_mix_f32",
    "hc_gates_f32",
    "hc_mix_f32",
    "stream_apply_f32",
    "split_q_and_gate_f32",
    "split_qkv_3way_f32",
    "linear_q4_k_gemv_coop_f32",
    // VENDORED-LOCAL: GPU-02 — test-only spin kernel (see KERNEL_SRC).
    "spin_f32",
    // VENDORED-LOCAL: MOE-01/MOE-02 — GPU routing + grouped MoE kernels.
    "moe_topk_softmax_f32",
    "moe_gate_up_act_q4_k_f32",
    "moe_gate_up_act_q6_k_f32",
    "moe_gate_up_act_q8_0_f32",
    "moe_down_scale_q4_k_f32",
    "moe_down_scale_q6_k_f32",
    "moe_down_scale_q8_0_f32",
    "moe_reduce_slots_f32",
];
