<?php
declare(strict_types=1);

namespace OaiyTest;

use Oaiy\Relay\B64;
use Oaiy\Relay\Crypto;
use Oaiy\Relay\Grants;
use Oaiy\Relay\Json;

/**
 * The recorded fixtures of the protocol package (platform/protocol/relay/v1/fixtures/), generated by driving the real relay
 * code: a pairing ceremony (Appendix A3's values) and the sealed tokens it produced, for the desktop and phone code that will
 * read them (DK-07). tests/fixtures.php writes them (`--write`) or checks the committed ones (`--check`).
 *
 * A sealed box is randomised by its ephemeral key, so these are recordings, not known answers: what is checked about a file is
 * that every value in it is what it says it is (the sealed token opens with the recipient's key, to a token of the right shape
 * whose SHA-256 the file records), and the same is checked again, without libsodium, by the independent verifiers
 * (verify_fixtures.py, verify_fixtures.mjs). The plaintext tokens themselves are never written down: a token is a credential
 * even when it belongs to a relay that no longer exists, and a secret scanner looks for the prefix.
 */
final class Fixtures
{
    public const DIR = 'protocol/relay/v1/fixtures';

    public static function dir(): string
    {
        return dirname(__DIR__, 3) . '/' . self::DIR;
    }

    /** JSON the way the package writes it: two-space indent, slashes and Unicode as they are, LF, a final newline. */
    public static function encode($v): string
    {
        $text = json_encode($v, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR);
        // PHP indents four spaces a level; the package's files (and Python's json.dump(indent=2)) use two. A line starts
        // with spaces only for indentation: a string cannot contain a raw newline.
        return preg_replace_callback('/^( +)/m', static fn(array $m): string => str_repeat(' ', intdiv(strlen($m[1]), 2)), $text) . "\n";
    }

    /**
     * One recorded exchange: what a client sent and what the relay answered. The desktop's token is named, not shown.
     * @param array<string,mixed> $res a Relay::call() answer
     * @return array<string,mixed>
     */
    private static function step(string $label, string $who, string $method, string $path, $body, array $res, ?string $note = null): array
    {
        $s = ['step' => $label, 'from' => $who, 'request' => ['method' => $method, 'path' => $path]];
        if ($body !== null) {
            $s['request']['body'] = $body;
        }
        $s['response'] = ['status' => $res['status'], 'body' => $res['json'] ?? new \stdClass()];
        if ($note !== null) {
            $s['note'] = $note;
        }
        return $s;
    }

    /**
     * The ceremony of Appendix A3, recorded through the real relay, and two more sealed tokens for the same phone key.
     * @return array{ceremony:array<string,mixed>,sealed:array<string,mixed>}
     */
    public static function pairing(): array
    {
        $v = Vectors::get('A3');
        $k = Vectors::get('keys');
        $r = Relay::make([], ['public_url' => 'https://relay.example.com']);
        $c = Ceremony::a3($r);

        $open = $c->open();
        $g1 = $c->get();
        $ans = $c->answer();
        $poll = $r->call($c->desk, 'GET', '/v1/poll');
        $dec = $c->decide();
        $g2 = $c->get();
        foreach ([$open, $g1, $ans, $poll, $dec, $g2] as $x) {
            if ($x['status'] >= 300) {
                throw new \RuntimeException('a step of the ceremony failed: ' . $x['body']);
            }
        }
        $steps = [
            self::step('desktop opens the rendezvous', 'desktop', 'POST', '/v1/pair', $c->createDoc(), $open, 'Authorization: the desktop\'s device token. The offer text is exactly the 778 bytes of Appendix A3.'),
            self::step('phone fetches the offer', 'phone', 'GET', '/v1/pair/' . $c->pid, null, $g1, 'No credential: the pid is the capability.'),
            self::step('phone posts its response', 'phone', 'POST', '/v1/pair/' . $c->pid . '/response', ['response' => $c->responseText()], $ans),
            self::step('desktop\'s poll returns the pair item', 'desktop', 'GET', '/v1/poll', null, $poll, 'The item id is the pid; from is "relay"; the body is the phone\'s response text, byte for byte.'),
            self::step('desktop approves', 'desktop', 'POST', '/v1/pair/' . $c->pid . '/decision', $c->decisionDoc(), $dec, 'The receipt is the desktop endpoint key\'s signature of Appendix A3 over the receipt document.'),
            self::step('phone reads the outcome', 'phone', 'GET', '/v1/pair/' . $c->pid, null, $g2, 'sealedToken opens with the phone\'s X25519 key (sealed-token.json says how); the receipt verifies under the desktop key pinned from the offer.'),
        ];
        $sealedFirst = $g2['json']['sealedToken'];
        $token = $c->openToken($sealedFirst);
        if ($token === null || strlen($token) !== 63) {
            throw new \RuntimeException('the recorded token does not open');
        }
        $cases = [self::sealedCase('the token of the recorded ceremony', $sealedFirst, $token)];
        for ($i = 2; $i <= 3; $i++) {
            $r2 = Relay::make([], ['public_url' => 'https://relay.example.com']);
            $c2 = Ceremony::a3($r2);
            $g = $c2->complete();
            $t = $c2->openToken($g['json']['sealedToken']);
            if ($t === null) {
                throw new \RuntimeException('a recorded token does not open');
            }
            $cases[] = self::sealedCase("another ceremony, token $i (a fresh ephemeral key each time)", $g['json']['sealedToken'], $t);
        }
        $raw = B64::dec($sealedFirst);
        $flip = function (int $pos) use ($raw): string {
            $x = $raw;
            $x[$pos] = chr(ord($x[$pos]) ^ 0x01);
            return B64::enc($x);
        };
        $refused = [
            ['label' => 'one bit of the ephemeral public key flipped', 'sealedToken' => $flip(5)],
            ['label' => 'one bit of the authentication tag flipped', 'sealedToken' => $flip(40)],
            ['label' => 'one bit of the ciphertext flipped', 'sealedToken' => $flip(60)],
            ['label' => 'the last byte removed', 'sealedToken' => B64::enc(substr($raw, 0, -1))],
            ['label' => 'a byte added', 'sealedToken' => B64::enc($raw . "\0")],
            ['label' => 'shorter than an ephemeral key and a tag (47 bytes)', 'sealedToken' => B64::enc(substr($raw, 0, 47))],
            ['label' => 'an ephemeral key of small order (the identity), with the rest of a real box', 'sealedToken' => B64::enc("\1" . str_repeat("\0", 31) . substr($raw, 32))],
            ['label' => 'an all-zero ephemeral key', 'sealedToken' => B64::enc(str_repeat("\0", 32) . substr($raw, 32))],
        ];
        $wrong = sodium_crypto_box_keypair();
        $sealed = [
            'protocol' => 'oaiy-relay/1',
            'title' => 'Sealed tokens from the pairing rendezvous',
            'about' => 'What GET /v1/pair/{pid} returns as sealedToken once the owner has approved, recorded from the real relay. The phone opens it with the X25519 secret it made for the pairing; nothing else opens it. See README.md in this folder for the format and for what a Rust reader calls.',
            'format' => [
                'box' => 'libsodium crypto_box_seal: an anonymous sealed box (X25519, XSalsa20-Poly1305)',
                'encoding' => 'base64url without padding (canonical: unused low bits zero)',
                'layout' => 'ephemeralPublic (32 bytes) || tag (16 bytes) || ciphertext (the same length as the plaintext)',
                'nonce' => 'BLAKE2b with a 24 byte output over ephemeralPublic || recipientPublic',
                'key' => 'crypto_box_beforenm: HSalsa20 over the X25519 shared secret of the recipient secret and ephemeralPublic',
                'plaintext' => 'the ASCII device token: "oaiyrt1." + 11 characters + "." + 43 characters, 63 bytes. It is never written in this file: plaintextSha256 is the check.',
                'refuse' => 'a box that does not authenticate, a length under 48 bytes, or an X25519 shared secret of all zeros (a small-order ephemeral key)',
            ],
            'recipient' => [
                'note' => 'The test phone of Appendix A3: a fixed public test key, never a real one.',
                'x25519Secret' => B64::enc(hex2bin($k['x25519Secrets']['phone'])),
                'x25519Public' => $k['x25519Public']['phone'],
            ],
            'opens' => $cases,
            'refused' => $refused,
            'wrongRecipient' => [
                'note' => 'The first recorded token does not open with this other key.',
                'x25519Secret' => B64::enc(sodium_crypto_box_secretkey($wrong)),
                'x25519Public' => B64::enc(sodium_crypto_box_publickey($wrong)),
            ],
        ];
        $ceremony = [
            'protocol' => 'oaiy-relay/1',
            'title' => 'The pairing ceremony of Appendix A3, recorded through the relay',
            'about' => 'Every request a desktop and a phone make in one pairing, and every answer, in order, recorded from the real relay with the fixed keys and values of Appendix A3 (vectors.json). A desktop, a phone and a stub relay can replay it. Times are the relay clock the recording ran on (1790000000). The device id of the desktop is the one Appendix A3 names.',
            'vector' => 'A3',
            'relay' => ['url' => 'https://relay.example.com', 'clock' => 1790000000],
            'pid' => $v['expected']['pid'],
            'sas' => $v['expected']['sasDisplay'],
            'steps' => $steps,
        ];
        return ['ceremony' => $ceremony, 'sealed' => $sealed];
    }

    /** @return array<string,mixed> */
    private static function sealedCase(string $label, string $sealed, string $token): array
    {
        return [
            'label' => $label, 'sealedToken' => $sealed, 'sealedBytes' => strlen((string)B64::dec($sealed)),
            'plaintextLength' => strlen($token), 'plaintextSha256' => hash('sha256', $token),
        ];
    }

    /** Open a sealed box with libsodium; false for anything that does not open, including a key that makes libsodium raise. */
    private static function open(string $sealedB64u, string $secret, string $public)
    {
        $bin = B64::dec($sealedB64u);
        if ($bin === null || strlen($bin) < 48) {
            return false;
        }
        try {
            return @sodium_crypto_box_seal_open($bin, sodium_crypto_box_keypair_from_secretkey_and_publickey($secret, $public));
        } catch (\SodiumException $e) {
            return false;
        }
    }

    /** Check a recording without regenerating it: every sealed token opens (or refuses) as the file says. @return list<string> problems */
    public static function checkSealed(array $doc): array
    {
        $bad = [];
        $secret = B64::decN($doc['recipient']['x25519Secret'] ?? '', 32);
        $public = B64::decN($doc['recipient']['x25519Public'] ?? '', 32);
        if ($secret === null || $public === null || !hash_equals(sodium_crypto_scalarmult_base($secret), $public)) {
            return ['the recipient key pair does not fit together'];
        }
        foreach ($doc['opens'] as $i => $c) {
            $open = self::open((string)$c['sealedToken'], $secret, $public);
            if ($open === false) {
                $bad[] = "opens[$i] does not open";
            } elseif (hash('sha256', $open) !== $c['plaintextSha256'] || strlen($open) !== $c['plaintextLength'] || preg_match('/^oaiyrt1\.[A-Za-z0-9_-]{11}\.[A-Za-z0-9_-]{43}$/D', $open) !== 1) {
                $bad[] = "opens[$i] opens to something else than the file says";
            }
        }
        foreach ($doc['refused'] as $i => $c) {
            if (self::open((string)$c['sealedToken'], $secret, $public) !== false) {
                $bad[] = "refused[$i] opens but must not";
            }
        }
        $w = B64::decN($doc['wrongRecipient']['x25519Secret'] ?? '', 32);
        $wp = B64::decN($doc['wrongRecipient']['x25519Public'] ?? '', 32);
        if ($w === null || $wp === null || self::open((string)$doc['opens'][0]['sealedToken'], $w, $wp) !== false) {
            $bad[] = 'the wrong recipient opens the first token';
        }
        return $bad;
    }

    /** Structure and rules of a recorded ceremony that do not depend on random values. @return list<string> problems */
    public static function checkCeremony(array $doc): array
    {
        $bad = [];
        $v = Vectors::get('A3');
        $steps = $doc['steps'] ?? [];
        if (count($steps) !== 6) {
            return ['the ceremony has ' . count($steps) . ' steps, not 6'];
        }
        $want = [[201, null], [200, 'open'], [202, 'answered'], [200, null], [200, 'approved'], [200, 'approved']];
        foreach ($steps as $i => $s) {
            if (($s['response']['status'] ?? 0) !== $want[$i][0]) {
                $bad[] = "step $i has status " . ($s['response']['status'] ?? '?');
            }
            if ($want[$i][1] !== null && ($s['response']['body']['state'] ?? null) !== $want[$i][1]) {
                $bad[] = "step $i is not in state {$want[$i][1]}";
            }
        }
        if (($steps[1]['response']['body']['offer'] ?? '') !== $v['expected']['offerText'] || ($steps[1]['response']['body']['mac'] ?? '') !== $v['expected']['offerMac']) {
            $bad[] = 'the offer the phone fetched is not the vector\'s';
        }
        if (($steps[3]['response']['body']['items'][0]['body'] ?? '') !== ($steps[2]['request']['body']['response'] ?? 'x')) {
            $bad[] = 'the desktop did not receive the phone\'s response text exactly';
        }
        if (($steps[5]['response']['body']['receipt']['signature'] ?? '') !== $v['expected']['receiptSignature']) {
            $bad[] = 'the receipt is not the vector\'s';
        }
        return $bad;
    }
}
