//! src/webgpu.c (webgpu.h's functions), compiled against the headers in include/ and kept whole in the library: nothing
//! of Rust's calls it, and a cdylib exports Rust's own symbols alone unless told to export the API's. Every other
//! function the headers declare is a weak stub (generated here) that says it is not compute: a program that binds the
//! whole API as it loads (Python's wgpu does) finds each one, and webgpu.c's own definitions win over the stubs.
use std::fmt::Write as _;

/// The headers' function declarations: (return type, name, parameters).
fn declarations(header: &str) -> Vec<(String, String, String)> {
    let mut out = Vec::new();
    for line in header.lines() {
        let line = line.trim();
        if line.starts_with("typedef") || line.starts_with('*') || line.starts_with('/') || line.starts_with('#') || !line.ends_with(';') {
            continue;
        }
        let line = line.trim_start_matches("WGPU_EXPORT ").trim_end_matches(';').trim_end_matches("WGPU_FUNCTION_ATTRIBUTE").trim();
        let (Some(open), true) = (line.find('('), line.ends_with(')')) else { continue };
        let head = &line[..open];
        let name_at = head.rfind(|c: char| !(c.is_ascii_alphanumeric() || c == '_')).map(|i| i + 1).unwrap_or(0);
        let name = &head[name_at..];
        if !name.starts_with("wgpu") {
            continue;
        }
        out.push((head[..name_at].trim().to_string(), name.to_string(), line[open + 1..line.len() - 1].to_string()));
    }
    out
}

fn main() {
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let mut stubs = String::from(
        "// generated by build.rs: every function of webgpu.h and wgpu.h, weak, for webgpu.c's to replace\n#include <stdio.h>\n#include <string.h>\n#include \"webgpu.h\"\n#include \"wgpu.h\"\nstatic void unsupported(const char* name) { fprintf(stderr, \"webgpu-tinygpu: %s is not compute, which is all this library does\\n\", name); }\n",
    );
    for header in ["include/webgpu.h", "include/wgpu.h"] {
        for (ret, name, params) in declarations(&std::fs::read_to_string(header).unwrap()) {
            let body = if ret == "void" { String::new() } else { format!(" {ret} r; memset(&r, 0, sizeof r); return r;") };
            writeln!(stubs, "__attribute__((weak, visibility(\"default\"))) {ret} {name}({params}) {{ unsupported(\"{name}\");{body} }}").unwrap();
        }
    }
    std::fs::write(out_dir.join("stubs.c"), stubs).unwrap();

    cc::Build::new()
        .file("src/webgpu.c")
        .file(out_dir.join("stubs.c"))
        .include("include")
        .define("WGPU_SHARED_LIBRARY", None)
        .define("WGPU_IMPLEMENTATION", None)
        .flag_if_supported("-std=gnu11")
        .flag_if_supported("-Wno-unused-parameter")
        .link_lib_modifier("+whole-archive")
        .compile("webgpu_c");
    for f in ["build.rs", "src/webgpu.c", "include/webgpu.h", "include/wgpu.h", "include/tgw.h"] {
        println!("cargo:rerun-if-changed={f}");
    }
    match std::env::var("CARGO_CFG_TARGET_OS").as_deref() {
        Ok("macos") | Ok("ios") => println!("cargo:rustc-cdylib-link-arg=-Wl,-exported_symbol,_wgpu*"),
        _ => println!("cargo:rustc-cdylib-link-arg=-Wl,--export-dynamic-symbol=wgpu*"),
    }
}
