"""Generate crates/dsv41/src/unicode.rs: the Unicode general-category ranges
the DeepSeek-V4.1 pre-tokenizer needs (letters, marks, numbers, punctuation,
symbols), from Python's unicodedata.

Usage: python tools/dsv41/gen_unicode.py > crates/dsv41/src/unicode.rs
"""

import sys
import unicodedata

CLASSES = {"L": "L", "M": "M", "N": "N", "P": "P", "S": "S"}


def cls(cp):
    return CLASSES.get(unicodedata.category(chr(cp))[0])


ranges = []
start, cur = 0, cls(0)
for cp in range(1, 0x110000):
    c = cls(cp)
    if c != cur:
        if cur is not None:
            ranges.append((start, cp - 1, cur))
        start, cur = cp, c
if cur is not None:
    ranges.append((start, 0x10FFFF, cur))

out = sys.stdout
out.write("//! Unicode general categories for the pre-tokenizer: letters, marks,\n")
out.write("//! numbers, punctuation and symbols, as sorted code-point ranges.\n")
out.write(f"//! Generated by tools/dsv41/gen_unicode.py from Unicode {unicodedata.unidata_version}; do not edit.\n\n")
out.write("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n")
out.write("pub enum Class {\n    Letter,\n    Mark,\n    Number,\n    Punct,\n    Symbol,\n    Other,\n}\n\n")
out.write("use Class::*;\n\n")
out.write("/// The general-category class of `c`.\n")
out.write("pub fn class(c: char) -> Class {\n")
out.write("    let cp = c as u32;\n")
out.write("    match RANGES.binary_search_by(|&(lo, hi, _)| {\n")
out.write("        if hi < cp {\n            std::cmp::Ordering::Less\n        } else if lo > cp {\n            std::cmp::Ordering::Greater\n        } else {\n            std::cmp::Ordering::Equal\n        }\n    }) {\n")
out.write("        Ok(i) => RANGES[i].2,\n        Err(_) => Other,\n    }\n}\n\n")
names = {"L": "Letter", "M": "Mark", "N": "Number", "P": "Punct", "S": "Symbol"}
out.write(f"#[rustfmt::skip]\nstatic RANGES: [(u32, u32, Class); {len(ranges)}] = [\n")
line = "   "
for lo, hi, c in ranges:
    item = f" (0x{lo:X}, 0x{hi:X}, {names[c]}),"
    if len(line) + len(item) > 96:
        out.write(line + "\n")
        line = "   "
    line += item
out.write(line + "\n];\n")
