//! Which Ed25519 keys the crate pins, registers and pairs with, and which it verifies with, against the relay's rule (`Crypto::isValidEd25519Public`, which a client must never be
//! more generous than: a key it pinned and the relay then refused would end a pairing late).
//!
//! The two questions have two answers (see `keys.rs`): **verifying** a signature is libsodium's verdict (`VerifyKey::from_bytes` and every `verify`, unchanged), and **pinning or
//! registering** a key is the relay's rule **and** the canonical encoding (`VerifyKey::from_bytes_registrable`). The keys below are the exact ones on which the crate and the relay
//! disagreed on the 249 edge cases of `rv/ed25519` (the review's corpus, regenerated by `tools/run-differentials.ps1`): the 33 the crate took and the relay refuses (a prime-order key
//! with a component of small order of order 4 or 8 beside it), and the 2 the relay takes and the crate refuses (a second, non-canonical spelling of a key that has a component of order 2).
//!
//! What the relay does take, found by the differential below: libsodium's `crypto_sign_ed25519_pk_to_curve25519` (the last line of `isValidEd25519Public`) accepts a key whose component
//! of small order is of order 1 **or 2** (its subgroup test looks at whether `X` is zero after multiplying by the group order, and the point of order 2, (0, -1), has `X` = 0), so the
//! relay's rule is a little more generous than its own comment says ("the prime-order subgroup"). The crate's registration is the prime-order subgroup exactly: it refuses everything the
//! relay refuses and also those, which no honest key is (every key made from a seed is of prime order).

mod common;

use curve25519_dalek::edwards::{CompressedEdwardsY, EdwardsPoint};
use oaiy_relay_core::keys::{Signer, VerifyKey};
use oaiy_relay_core::Error;

/// Keys that the crate's verifier accepted and the relay refuses (`isValidEd25519Public` false): in the corpus, in 72 rows.
const REFUSED_BY_THE_RELAY: [&str; 33] = [
    "017522d343690fea7e8cb5d69dd1f0a7152f3c488bbde08f468327b5c0d599e8",
    "0300000000000000000000000000000000000000000000000000000000000000",
    "0300000000000000000000000000000000000000000000000000000000000080",
    "0400000000000000000000000000000000000000000000000000000000000000",
    "0400000000000000000000000000000000000000000000000000000000000080",
    "0500000000000000000000000000000000000000000000000000000000000000",
    "0500000000000000000000000000000000000000000000000000000000000080",
    "0600000000000000000000000000000000000000000000000000000000000000",
    "0600000000000000000000000000000000000000000000000000000000000080",
    "0a00000000000000000000000000000000000000000000000000000000000000",
    "0a00000000000000000000000000000000000000000000000000000000000080",
    "0e00000000000000000000000000000000000000000000000000000000000000",
    "0e00000000000000000000000000000000000000000000000000000000000080",
    "0f00000000000000000000000000000000000000000000000000000000000000",
    "0f00000000000000000000000000000000000000000000000000000000000080",
    "1000000000000000000000000000000000000000000000000000000000000000",
    "1000000000000000000000000000000000000000000000000000000000000080",
    "1200000000000000000000000000000000000000000000000000000000000000",
    "1200000000000000000000000000000000000000000000000000000000000080",
    "24397ef45454c5e0b0d5a7ce7601e77df68a52253a788116d17a4744e219fdc2",
    "37af5726fd95509dc8df3c58fce3fb64504d7662fc9968d7abe44a54fead1972",
    "4a542b712ed3c93840af0201f9e78d3592211b3f18fcdf1ace6a73c240d87e20",
    "73f5624a4fe334ec76bb9edacc198847d2a2d318313cb71a7b7731b1c6f72cbe",
    "7563397a1042a332d33e43f36e4b0bb6e440646a20bc5d67ce124f8db4290569",
    "789cc685efbd5ccd2cc1bc0c91b4f4491bbf9b95df43a29831edb0724bd6fa96",
    "7a0a9db5b01ccb138944612533e677b82d5d2ce7cec348e58488ce4e3908d341",
    "8ad1c77959626f400e865f424225331fb7b452d83cbc70d8da234b83f92d2b8c",
    "a3abd48ed12c36c7bf50fdfe061872ca6ddee4c0e70320e531958c3dbf2781df",
    "aad1c77959626f400e865f424225331fb7b452d83cbc70d8da234b83f92d2bcc",
    "abd1c77959626f400e865f424225331fb7b452d83cbc70d8da234b83f92d2b8c",
    "b650a8d9026aaf623720c3a7031c049bafb2899d03669728541bb5ab0152e68d",
    "c9c6810babab3a1f4f2a583189fe18820975addac5877ee92e85b8bb1de6023d",
    "ec8add2cbc96f01581734a29622e0f58ead0c3b774421f70b97cd84a3f2a6617",
];

/// Keys that the relay accepts and the crate refuses (`NonCanonicalKey`): `2^255 - 10` is `p + 9`, the second spelling of the key whose canonical y is 9 (and its sign-bit twin).
const ONLY_THE_RELAY_TAKES: [&str; 2] =
    ["f6ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", "f6ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"];

/// Small-order points: one of order 2, two of order 8 and one of order 4 (the relay's own list; the identity is the fifth and adds nothing).
const TORSION: [&str; 4] = [
    "ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f",
    "26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc05",
    "c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac037a",
    "0000000000000000000000000000000000000000000000000000000000000000",
];

fn key(hex: &str) -> [u8; 32] {
    common::unhex32(hex)
}

fn point(bytes: &[u8; 32]) -> EdwardsPoint {
    CompressedEdwardsY(*bytes).decompress().expect("a point")
}

#[test]
fn the_verifier_takes_the_keys_the_relay_refuses_and_registration_does_not() {
    for hex in REFUSED_BY_THE_RELAY {
        let bytes = key(hex);
        // The verifier is libsodium's: these keys are canonical and not of small order, so it builds them (and it verifies with them as libsodium does: see the differential).
        let verifier = VerifyKey::from_bytes(&bytes).unwrap_or_else(|e| panic!("{hex}: the verifier refused it: {e}"));
        assert!(!verifier.is_registrable(), "{hex}");
        assert!(!point(&bytes).is_torsion_free(), "{hex}: it has a component of small order");
        // Registration is the relay's rule: refused, with a reason that says so.
        let refused = VerifyKey::from_bytes_registrable(&bytes).unwrap_err();
        assert!(matches!(refused, Error::Invalid(w) if w.contains("prime-order")), "{hex}: {refused:?}");
        assert!(VerifyKey::from_b64u_registrable(&oaiy_relay_core::b64::encode(&bytes)).is_err(), "{hex}");
    }
}

#[test]
fn the_two_non_canonical_spellings_the_relay_takes_are_refused_by_both_constructors() {
    for hex in ONLY_THE_RELAY_TAKES {
        let bytes = key(hex);
        assert!(matches!(VerifyKey::from_bytes(&bytes), Err(Error::Crypto(_))), "{hex}: a verifier never takes y + p");
        assert!(VerifyKey::from_bytes_registrable(&bytes).is_err(), "{hex}: nor does registration, which is stricter than the relay here on purpose");
        // The point is not in the prime-order subgroup either (it has a component of order 2, which the relay's libsodium lets through) and its spelling is not the canonical one,
        // which gives the same key a second thumbprint: the relay takes it, libsodium will not verify a signature with it, and the crate takes neither.
        assert!(!point(&bytes).is_torsion_free(), "{hex}");
    }
}

#[test]
fn every_key_an_honest_party_makes_is_registrable_and_verifies_as_before() {
    for _ in 0..200 {
        let signer = Signer::generate().unwrap();
        let public = signer.verify_key();
        assert!(public.is_registrable());
        assert_eq!(VerifyKey::from_bytes_registrable(&public.to_bytes()).unwrap(), public);
        let signature = signer.sign_b64u(oaiy_relay_core::keys::SignDomain::Cmd, &[b"a command"]);
        public.verify_b64u(oaiy_relay_core::keys::SignDomain::Cmd, &[b"a command"], &signature).unwrap();
    }
}

/// One php process answers for every key: `isValidEd25519Public` of the relay's own `Crypto.php`, one answer a line.
fn relay_verdicts(php: &std::path::Path, keys: &[[u8; 32]]) -> Vec<bool> {
    let dir = std::path::PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join(format!("ed25519-keys-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let (script, input) = (dir.join("verdicts.php"), dir.join("keys.txt"));
    std::fs::write(
        &script,
        "<?php\ndefine('OAIY_RELAY', 1);\nrequire $argv[1];\nforeach (file($argv[2], FILE_IGNORE_NEW_LINES) as $h) { echo Oaiy\\Relay\\Crypto::isValidEd25519Public(hex2bin($h)) ? \"1\\n\" : \"0\\n\"; }\n",
    )
    .unwrap();
    let lines: Vec<String> = keys.iter().map(|k| common::hex(k)).collect();
    std::fs::write(&input, lines.join("\n")).unwrap();
    let out = std::process::Command::new(php).arg(&script).arg(common::php::relay_root().join("src/Crypto.php")).arg(&input).output().expect("php");
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let _ = std::fs::remove_dir_all(&dir);
    String::from_utf8(out.stdout).unwrap().lines().map(|l| l == "1").collect()
}

#[test]
fn registration_is_never_more_generous_than_the_relay_on_the_corpus_honest_keys_mixed_order_keys_and_random_bytes() {
    let Some(php) =
        common::php::php_or_skip("registration_is_never_more_generous_than_the_relay_on_the_corpus_honest_keys_mixed_order_keys_and_random_bytes")
    else {
        return;
    };
    let mut keys: Vec<[u8; 32]> = Vec::new();
    keys.extend(REFUSED_BY_THE_RELAY.iter().map(|h| key(h)));
    keys.extend(ONLY_THE_RELAY_TAKES.iter().map(|h| key(h)));
    let honest_from = keys.len();
    keys.extend((0..150).map(|_| Signer::generate().unwrap().verify_key().to_bytes()));
    let torsion_from = keys.len();
    // An honest key plus each point of small order in turn: order 2 first, then the two of order 8 and the one of order 4.
    let torsion: Vec<EdwardsPoint> = TORSION.iter().map(|h| point(&key(h))).collect();
    for _ in 0..150 {
        let honest = point(&Signer::generate().unwrap().verify_key().to_bytes());
        for t in &torsion {
            keys.push((honest + t).compress().to_bytes());
        }
    }
    let random_from = keys.len();
    // Random bytes (most are no point at all).
    let mut rng = common::Rng(0xed25519);
    for _ in 0..600 {
        keys.push(rng.bytes(32).try_into().unwrap());
    }
    let relay = relay_verdicts(&php, &keys);
    assert_eq!(relay.len(), keys.len());
    let (mut relay_takes, mut verifier_alone, mut order_two_taken_by_the_relay) = (0, 0, 0);
    for (n, (bytes, relay_takes_it)) in keys.iter().zip(&relay).enumerate() {
        let ours = VerifyKey::from_bytes_registrable(bytes).is_ok();
        let hex = common::hex(bytes);
        // The property that matters: the crate never registers a key the relay refuses.
        assert!(!ours || *relay_takes_it, "the crate registers a key the relay refuses: {hex}");
        if n < honest_from {
            if ONLY_THE_RELAY_TAKES.iter().any(|h| key(h) == *bytes) {
                assert!(*relay_takes_it && !ours, "{hex}");
            } else {
                assert!(!relay_takes_it && !ours, "{hex}: the corpus' keys the relay refuses");
            }
        } else if n < torsion_from {
            assert!(ours && *relay_takes_it, "{hex}: an honest key is taken by both");
        } else if n < random_from {
            // An honest key plus a point of order 4 or 8 is refused by the relay (and taken by the verifier alone); plus the point of order 2 the relay's libsodium lets it through (noted,
            // not asserted: it is libsodium's). The crate refuses all of them.
            let which = (n - torsion_from) % 4;
            assert!(!ours, "{hex}: honest plus torsion {which}");
            if which == 0 {
                order_two_taken_by_the_relay += usize::from(*relay_takes_it);
            } else {
                assert!(!relay_takes_it, "{hex}: the relay refuses an honest key plus a point of order 4 or 8 (torsion {which})");
            }
        }
        relay_takes += usize::from(*relay_takes_it);
        verifier_alone += usize::from(VerifyKey::from_bytes(bytes).is_ok() && !ours);
    }
    eprintln!(
        "{} keys: the relay takes {relay_takes}, among them {order_two_taken_by_the_relay} of 150 honest keys plus a point of order 2; the verifier alone takes {verifier_alone} that registration refuses",
        keys.len()
    );
    assert!(relay_takes >= 150 && verifier_alone >= 450, "{relay_takes} {verifier_alone}");
}
